### ISSUE TITLE
Private repos

### ISSUE THREAD

**Issue by giuliojiang** [HPCE/hpce-2017-cw4#20]
Our private repos haven't been created yet?

We don't have permissions to fork to HPCE organization.

Forking to our private accounts would likely break your automated tests and also make the repo public.

**Comment by m8pple** [comment]
Yes, it needs me to create them otherwise things won't work properly. As
far as I was aware they were all created, as I ran the script around a week
ago, but this actually doesn't seem to be the case, as most are missing
(it just so happens that the couple I randomly sampled were actually created).

Thanks for pointing it out.

I've kicked the script off again, with some logic to avoid replacing the existing
repos.

As for the cause, according to my system logs it looks like Windows 10 helpfully
restarted itself not long after I started the script to create the cw4 repos (it takes
about two hours to run). It's increasingly difficult to tell the difference between
"Important System Update requiring restart" (Microsoft's view) and
"Windows Crashed" (as anyone else trying to use it for long-term compute tasks
would see it), particularly given they try to disable any mechanisms which allow
users to control it.
