### ISSUE TITLE
cat: write error: Broken pipe

### ISSUE THREAD

**Issue by natoucs** [HPCE/hpce-2017-cw4#23]
`cat: write error: Broken pipe` when trying `cat /dev/urandom | head -c 1048576 > w/random1M.bin` at the beginning of cw4.

Anybody has a similar error or an idea of why this is happening ?

**Comment by m8pple** [comment]
The error is coming from `cat`, because it has an infinite stream of data that it would like
to produce/write, but the consuming side (`head -c 1048576`) is only going to consume/read
a finite amount of data. Internally `cat` looks something like:
```
char buffer[size];
while( 1 ){
   got=read(src, size, buffer);
   if(got <= 0){
      // Handle error or end of file
   }
   done=write(dst, got, buffer);   // Ignoring need for retry loop
   if( done != got){
      // handle error
   }
}
```
In our situation, the `read` will always succeed and produce more data, but eventually
the `write` will fail with , just because `head` has consumed all the data it wants,
and has exited. The error code is `EPIPE` - [see here](https://linux.die.net/man/3/write).

Some implementations of `cat` treat it as an error and print a message, while others don't.
Just in case, you can check that the output file is still 1048576 bytes long in order to
check that all the data made it over:
```
ls -la w/random1M.bin
```

**Comment by natoucs** [comment]
`ls -la w/random1M.bin` yields `-rw-rw-r-- 1 nathan nathan 1048576 nov.   6 17:15 w/random1M.bin`
So everything is fine: ignore this error if your file size is coherent.
Thank you for the detailed explanation @m8pple !
